@api = http://localhost:3000

GET {{api}}/users

###


POST {{api}}/login
Content-Type: application/json

{
    "usuario": "tulio1",
    "contraseña": "tulio123"
}


###

POST {{api}}/users
Content-Type: application/json


{
    "nombre": "prueba",
    "apellido": "prueba",
    "email": "example@gmail.com",
    "telefono": 123456789,
    "usuario": "prueba1",
    "contraseña": "prueba123"
}

###

GET {{api}}/users/7


###

DELETE {{api}}/users/3


###

PUT {{api}}/users/7
Content-Type: application/json


{
    "nombre": "tulio",
    "apellido": "marin",
    "email": "example@gmail.com",
    "telefono": 123456777,
    "usuario": "tulio1",
    "contraseña": "tulio123"
}